### PR TITLE
Ned testing the OSPR bot, please ignore.

### PR DESCRIPTION
**Pull request by nedbat**
I'm seeing if my Jira service credentials can write to TNL.

### CODE REVIEW

**Comment by nedbat** [comment]
again

**Comment by nedbat** [comment]
now?

**Comment by nedbat** [comment]
this won't either...

**Comment by nedbat** [comment]
now?

**Comment by nedbat** [comment]
ugh, it will crash again.

**Comment by nedbat** [comment]
But now it won't.

**Comment by nedbat** [comment]
hey

**Comment by nedbat** [comment]
more

**Comment by nedbat** [comment]
doit

**Comment by nedbat** [comment]
ping

**Comment by nedbat** [comment]
more

**Comment by nedbat** [comment]
xyz

**Comment by nedbat** [comment]
hi

**Comment by nedbat** [comment]
fixed the jira mapping defaults.

**Comment by openedx-webhooks** [comment]
I've created issue [ARCHBOM-2167](https://2u-internal.atlassian.net/browse/ARCHBOM-2167) in private 2U Jira.

**Pull request closed without merging**
