### PR TITLE
Testing the bot!

### PR DESCRIPTION
**Pull request by nedbat**

### CODE REVIEW

**Comment by nedbat** [comment]
/2u-jira create in ARCHBOM, please.

**Comment by nedbat** [comment]
/2u-jira create in archbom if you don't mind

**Comment by nedbat** [comment]
2u-jira: create   in  archbom, please.

**Comment by nedbat** [comment]
2u-jira: create   in  archbom, please.

**Comment by nedbat** [comment]
2u-jira: create in archbom, please if you wouldn't mind.

**Comment by nedbat** [comment]
2u-jira: create in archbom, kthxbye

**Comment by nedbat** [comment]
2u-jira: create in archbom

**Comment by nedbat** [comment]
2u-jira: create in archbom

**Comment by nedbat** [comment]
2u-jira: create in archbom.

**Comment by nedbat** [comment]
2u-jira: create in archbom

**Comment by nedbat** [comment]
2u-jira: create in archbom

**Comment by nedbat** [comment]
2u-jira: create in archbom.

**Comment by nedbat** [comment]
Hey there.

**Comment by nedbat** [comment]
A comment on a pull request

**Comment by nedbat** [comment]
pr comment.

**Comment by nedbat** [comment]
hello

**Comment by nedbat** [comment]
will this do something?

**Comment by nedbat** [comment]
A comment on an open PR.

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @nedbat! Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by nedbat** [comment]
does it work?

**Comment by nedbat** [comment]
maybe now?

**Comment by nedbat** [comment]
of course it will work now.

**Comment by nedbat** [comment]
maybe issuetype=Task?

**Comment by nedbat** [comment]
no custom fields.

**Comment by nedbat** [comment]
seriously now.

**Comment by openedx-webhooks** [comment]
I've created issue [ARCHBOM-2164](https://2u-internal.atlassian.net/browse/ARCHBOM-2164) in private 2U Jira.

**Comment by nedbat** [comment]
now I can comment again, and nothing new happens.

**Pull request closed without merging**
