### PR TITLE
Ned testing the Bot

### PR DESCRIPTION
**Pull request by nedbat**

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
I've created issue [ARCHBOM-2171](https://2u-internal.atlassian.net/browse/ARCHBOM-2171) in the private 2U Jira.

**Comment by nedbat** [comment]
Hello.

**Comment by nedbat** [comment]
Is a comment after merging ok?

**Review by nedbat — COMMENTED** [review]
This is a review after merging.

**Pull request merged**
